# Generated by Django 3.2.16 on 2023-01-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230122_1738'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_name_author',
        ),
    ]
